from . import material
from . import color
from . import brand
from . import frame_shape
from . import product_template
from . import stock_picking
from . import inventory_adjustment
from . import stock_location
from . import stock_return_picking
from . import stock_quant
from . import stock_move_line
from . import stock_move
from . import stock_warehouse
from . import product_label_layout