from . import product
from . import pos_order_refraction
from . import pos_order
from . import pos_category
from . import res_partner
from . import loyalty_program
from . import loyalty_reward
from . import loyalty_generate_code
from . import pos_promotion
from . import pos_config
from . import stock_picking