{
    'name': 'Thinq - Inventory',
    'version': '1.0',
    'description': 'Customization for Thinq module in Kacamatamoo (Inventory)',
    'summary': 'Customization for Thinq module in Kacamatamoo (Inventory)',
    'author': 'Thinq Technology',
    'website': 'https://thinq-tech.id',
    'license': 'LGPL-3',
    'category': 'custom',
    'sequence': 100,
    'depends': [
        'stock',
        'product',
        'thinq_base',
        'sale_management',
        'thinq_sale',
        'sale',
        'web',
        'barcodes',
        'website',
        'stock_picking_whole_scrap', #ijin nambahin ini drey
    ],
    'external_dependencies': {
        'python': ['qrcode', 'PIL'],
    },
    'data': [
            'data/intermediate_scrap.xml',
            'reports/action.xml',
            'reports/custom_label_template.xml',
            'reports/shipping_label_template.xml',
            'reports/delivery_slip_custom.xml',
            'reports/picking_label_template.xml',
            'wizard/stock_picking_whole_scrap.xml',
            'wizard/stock_picking_box.xml',
            'wizard/stock_picking_label_layout.xml',
            'views/material.xml',
            'views/color.xml',
            'views/brand.xml',
            'views/frame_shape.xml',
            'views/product_template.xml',
            'views/stock_picking.xml',
            # 'views/stock_return_picking.xml',
            'views/stock_scrap.xml',
            'views/location_report_views.xml',
            'views/stock_move_line.xml',
            'views/menu.xml',
            'views/inventory_adjustment_views.xml',
            'views/stock_location_views.xml',
            'views/shipment_info_template.xml',
            'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_backend': [
            'thinq_inventory/static/src/js/barcode.js',
        ],
    },
    'demo': [
    ],
    'auto_install': False,
    'application': False,
}